// Compiler: canonical scenario -> framescope stimulus TOML (SC-1, needs FS-1 for `line`).

import { FRAMESCOPE_MOUSE_DEFAULT } from '../core/constants.ts';
import type { MouseSnapshot } from '../core/state.ts';
import type { CanonicalScenario } from './types.ts';

export interface StimOptions {
  /** Scan line at which inputs change; default 10 = first line of the vertical back porch (D-008). */
  line: number;
  /** Added to golden frame indices to get framescope frame numbers. */
  frameOffset: number;
  /** framescope virtual-input names. */
  keys: { x: string; y: string; left: string; middle: string; right: string };
  /** Mouse state framescope starts with (its [virtual_inputs] defaults). */
  baseline: MouseSnapshot;
}

export const DEFAULT_STIM_OPTIONS: StimOptions = {
  line: 10,
  frameOffset: 0,
  keys: { x: 'mouse.x', y: 'mouse.y', left: 'mouse.left', middle: 'mouse.middle', right: 'mouse.right' },
  baseline: { ...FRAMESCOPE_MOUSE_DEFAULT },
};

const tomlString = (s: string) => JSON.stringify(s);
const comment = (s: string) => s.split('\n').map((l) => `# ${l}`.trimEnd()).join('\n');

export function compileStim(sc: CanonicalScenario, partial: Partial<StimOptions> = {}): string {
  const o: StimOptions = { ...DEFAULT_STIM_OPTIONS, ...partial, keys: { ...DEFAULT_STIM_OPTIONS.keys, ...partial.keys } };
  const out: string[] = [];
  out.push(comment(`Scenario: ${sc.name}`));
  if (sc.description) out.push(comment(sc.description));
  out.push(comment(`Generated by golden (npm run golden -- stim). Do not edit by hand.`));
  out.push(comment(`Golden frames: ${sc.frameCount}; framescope frame = golden frame + ${o.frameOffset}; inputs change on line ${o.line}.`));
  out.push(comment(`Run at least ${sc.frameCount + o.frameOffset} frames.`));
  for (const c of sc.checkpoints) {
    out.push(comment(`checkpoint ${c.label}: golden frame ${c.frame}, framescope frame ${c.frame + o.frameOffset}`));
  }
  out.push('', `frames = ${sc.frameCount + o.frameOffset}`);
  let prev = o.baseline;
  sc.frames.forEach((f, i) => {
    const set: string[] = [];
    if (f.x !== prev.x) set.push(`${tomlString(o.keys.x)} = ${f.x}`);
    if (f.y !== prev.y) set.push(`${tomlString(o.keys.y)} = ${f.y}`);
    for (const b of ['left', 'middle', 'right'] as const) {
      if (f[b] !== prev[b]) set.push(`${tomlString(o.keys[b])} = ${f[b] ? 1 : 0}`);
    }
    if (set.length) {
      out.push('', '[[event]]', `frame = ${i + o.frameOffset}`, `line = ${o.line}`, `set = { ${set.join(', ')} }`);
    }
    prev = f;
  });
  return out.join('\n') + '\n';
}

/** Minimal parser for the TOML subset compileStim emits (round-trip tests, tooling). */
export function parseStim(toml: string, partial: Partial<StimOptions> = {}): { frame: number; line: number; set: Record<string, number> }[] {
  const o: StimOptions = { ...DEFAULT_STIM_OPTIONS, ...partial };
  const events: { frame: number; line: number; set: Record<string, number> }[] = [];
  let cur: { frame: number; line: number; set: Record<string, number> } | null = null;
  for (const raw of toml.split('\n')) {
    const l = raw.trim();
    if (!l || l.startsWith('#')) continue;
    if (l === '[[event]]') {
      cur = { frame: -1, line: o.line, set: {} };
      events.push(cur);
      continue;
    }
    const m = /^(\w+)\s*=\s*(.*)$/.exec(l);
    if (m?.[1] === 'frames' && !cur) continue;
    if (!m || !cur) throw new Error(`unexpected line: ${l}`);
    if (m[1] === 'frame') cur.frame = Number(m[2]);
    else if (m[1] === 'line') cur.line = Number(m[2]);
    else if (m[1] === 'set') {
      const body = m[2]!.replace(/^\{|\}$/g, '');
      for (const kv of body.split(',')) {
        const mm = /^\s*"([^"]+)"\s*=\s*(-?\d+)\s*$/.exec(kv);
        if (mm) cur.set[mm[1]!] = Number(mm[2]);
      }
    }
  }
  return events;
}
