#*****************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# metacircuit.tcl: Tcl script for re-creating project 'metacircuit'
#
# Generated by Vivado on Mon Apr 13 18:17:55 +0800 2026
# IP Build 2256618 on Thu Jun 14 22:10:49 MDT 2018
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (metacircuit.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/C/EE2026/metacircuit/src/design/solver/BackendFetchers.v"
#    "C:/C/EE2026/metacircuit/src/design/rendering/ButtonVGA.v"
#    "C:/C/EE2026/metacircuit/src/design/Keyboard/Calculator.v"
#    "C:/C/EE2026/metacircuit/src/design/rendering/CircuitCanvas.v"
#    "C:/C/EE2026/metacircuit/src/design/common/ClockDivider.v"
#    "C:/C/EE2026/metacircuit/src/design/Dashboard/ComponentPropertyPanel.v"
#    "C:/C/EE2026/metacircuit/src/design/rendering/DummyDataGenerate.v"
#    "C:/C/EE2026/metacircuit/src/design/Dashboard/DynamicTextBox.v"
#    "C:/C/EE2026/metacircuit/src/design/common/FloodQueueStore.v"
#    "C:/C/EE2026/metacircuit/src/design/Dashboard/FontROM.v"
#    "C:/C/EE2026/metacircuit/src/design/interaction/InteractionController.v"
#    "C:/C/EE2026/metacircuit/src/design/interaction/InteractionFrameCapture.v"
#    "C:/C/EE2026/metacircuit/src/design/rendering/KeyboardVGA.v"
#    "C:/C/EE2026/metacircuit/src/design/driver/Oled_Display.v"
#    "C:/C/EE2026/metacircuit/src/design/common/PingPongBuffer.v"
#    "C:/C/EE2026/metacircuit/src/design/matrix/ResultMatrixStore.v"
#    "C:/C/EE2026/metacircuit/src/design/common/SimpleDualRam.v"
#    "C:/C/EE2026/metacircuit/src/design/common/SimpleRam.v"
#    "C:/C/EE2026/metacircuit/src/design/rendering/ToolbarVGA.v"
#    "C:/C/EE2026/metacircuit/src/design/uart/UartTx.v"
#    "C:/C/EE2026/metacircuit/src/design/driver/VGAControl.v"
#    "C:/C/EE2026/metacircuit/src/design/matrix/VisitedMatrixStore.v"
#    "C:/C/EE2026/metacircuit/src/design/rendering/WaveformPlot.v"
#    "C:/C/EE2026/metacircuit/src/design/interaction/WireDrawMode.v"
#    "C:/C/EE2026/metacircuit/src/design/Keyboard/one_bit_adder.v"
#    "C:/C/EE2026/metacircuit/src/design/common/ExtractComponentNodesCombPkg.sv"
#    "C:/C/EE2026/metacircuit/src/design/solver/FloodingBackendWrapper.sv"
#    "C:/C/EE2026/metacircuit/src/design/common/FloodingCombPkg.sv"
#    "C:/C/EE2026/metacircuit/src/design/solver/extract_component_nodes.sv"
#    "C:/C/EE2026/metacircuit/src/design/solver/flooding_core.sv"
#    "C:/C/EE2026/metacircuit/src/design/rendering/MouseDisplay.vhd"
#    "C:/C/EE2026/metacircuit/src/design/driver/Mouse_Control.vhd"
#    "C:/C/EE2026/metacircuit/src/design/driver/Ps2Interface.vhd"
#    "C:/C/EE2026/metacircuit/src/design/rendering/GlobalRender_top.v"
#    "C:/C/EE2026/metacircuit/src/ip/floating_point_fma/floating_point_fma.xci"
#    "C:/C/EE2026/metacircuit/src/ip/floating_point_div/floating_point_div.xci"
#    "C:/C/EE2026/metacircuit/src/design/uart/Hex7SegMux.v"
#    "C:/C/EE2026/metacircuit/src/design/solver_board/UartRx.v"
#    "C:/C/EE2026/metacircuit/src/design/floating_point/fpo_div.v"
#    "C:/C/EE2026/metacircuit/src/design/floating_point/fpo_fma.v"
#    "C:/C/EE2026/metacircuit/src/design/solver_board/BcdUnitToFp32Rom.sv"
#    "C:/C/EE2026/metacircuit/src/design/solver_board/SolverDcPipeline.sv"
#    "C:/C/EE2026/metacircuit/src/design/matrix/SolverMatrixStore.sv"
#    "C:/C/EE2026/metacircuit/src/design/solver_board/SolverUartLineTransmitter.sv"
#    "C:/C/EE2026/metacircuit/src/design/matrix/SolverVectorStore.sv"
#    "C:/C/EE2026/metacircuit/src/design/common/StampingCombPkg.sv"
#    "C:/C/EE2026/metacircuit/src/design/common/StampingNetlistStore.sv"
#    "C:/C/EE2026/metacircuit/src/design/solver_board/UartLineAssembler.sv"
#    "C:/C/EE2026/metacircuit/src/design/solver_board/UartPacketParser.sv"
#    "C:/C/EE2026/metacircuit/src/design/solver/solve_core_dc.sv"
#    "C:/C/EE2026/metacircuit/src/design/solver_board/SolverBoard_top.sv"
#    "C:/C/EE2026/metacircuit/src/design/Dashboard/TextBox.v"
#    "C:/C/EE2026/metacircuit/src/design/Dashboard/CompactDigitROM.v"
#    "C:/C/EE2026/metacircuit/src/design/Dashboard/MatrixDisplay.v"
#    "C:/C/EE2026/metacircuit/src/design/uart/UART_FrameDemo_top.v"
#    "C:/C/EE2026/metacircuit/src/ip/floating_point_to_fixed_16_16/floating_point_to_fixed_16_16.xci"
#    "C:/C/EE2026/metacircuit/src/design/Keyboard/Keyboard.v"
#    "C:/C/EE2026/metacircuit/src/design/floating_point/fpo_tofixed.v"
#    "C:/C/EE2026/metacircuit/src/design/matrix/lu_core.sv"
#    "C:/C/EE2026/metacircuit/src/design/common/ClockDividerMs.v"
#    "C:/C/EE2026/metacircuit/src/design/matrix/LUdecomp.v"
#    "C:/C/EE2026/metacircuit/src/design/matrix/bmatrixStore.v"
#    "C:/C/EE2026/metacircuit/src/design/Dashboard/TextDisplay.v"
#    "C:/C/EE2026/metacircuit/src/design/matrix/PortGridStore.v"
#    "C:/C/EE2026/metacircuit/src/design/common/CanvasBufferRam.v"
#    "C:/C/EE2026/metacircuit/src/design/matrix/matrixStore.v"
#    "C:/C/EE2026/metacircuit/src/design/Dashboard/DynamicTextDisplay.v"
#    "C:/C/EE2026/metacircuit/src/design/solver_board/bcd_unit_to_fp32_rom.mem"
#    "C:/C/EE2026/metacircuit/src/constraint/basys3.xdc"
#    "C:/C/EE2026/metacircuit/src/constraint/basys3_solver_board.xdc"
#    "C:/C/EE2026/metacircuit/src/testbench/SolveCoreDc_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/VisitedMatrixStore_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/StampingCombPkg_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/InteractionController_test.v"
#    "C:/C/EE2026/metacircuit/src/testbench/StampingNetlistStore_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/FloodingCombPkg_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/FloodQueueStore_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/Canvas_test.v"
#    "C:/C/EE2026/metacircuit/src/testbench/SolverVectorStore_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/misc/CounterQuiz_test.v"
#    "C:/C/EE2026/metacircuit/src/testbench/FloodingCore_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/StampingVectorStore_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/LU_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/CircuitCanvas_left_edge_test.v"
#    "C:/C/EE2026/metacircuit/src/testbench/PingPongBuffer_test.v"
#    "C:/C/EE2026/metacircuit/src/testbench/InteractionCanvas_test.v"
#    "C:/C/EE2026/metacircuit/src/testbench/PortGridStore_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/DynamicTextDisplay_tb.v"
#    "C:/C/EE2026/metacircuit/src/testbench/StampingMatrixStore_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/FP_test.v"
#    "C:/C/EE2026/metacircuit/src/testbench/LU_hls_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/SolverMatrixStore_test.sv"
#    "C:/C/EE2026/metacircuit/src/testbench/FP_wrapper_test.v"
#    "C:/C/EE2026/metacircuit/src/testbench/ResultMatrixStore_test.sv"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "metacircuit"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "metacircuit.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/metacircuit"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a35tcpg236-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.uses_pr" -value "1" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7a35tcpg236-1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "4" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "4" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "4" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "4" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "4" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "4" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "4" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "21" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/src/design/solver/BackendFetchers.v"] \
 [file normalize "${origin_dir}/src/design/rendering/ButtonVGA.v"] \
 [file normalize "${origin_dir}/src/design/Keyboard/Calculator.v"] \
 [file normalize "${origin_dir}/src/design/rendering/CircuitCanvas.v"] \
 [file normalize "${origin_dir}/src/design/common/ClockDivider.v"] \
 [file normalize "${origin_dir}/src/design/Dashboard/ComponentPropertyPanel.v"] \
 [file normalize "${origin_dir}/src/design/rendering/DummyDataGenerate.v"] \
 [file normalize "${origin_dir}/src/design/Dashboard/DynamicTextBox.v"] \
 [file normalize "${origin_dir}/src/design/common/FloodQueueStore.v"] \
 [file normalize "${origin_dir}/src/design/Dashboard/FontROM.v"] \
 [file normalize "${origin_dir}/src/design/interaction/InteractionController.v"] \
 [file normalize "${origin_dir}/src/design/interaction/InteractionFrameCapture.v"] \
 [file normalize "${origin_dir}/src/design/rendering/KeyboardVGA.v"] \
 [file normalize "${origin_dir}/src/design/driver/Oled_Display.v"] \
 [file normalize "${origin_dir}/src/design/common/PingPongBuffer.v"] \
 [file normalize "${origin_dir}/src/design/matrix/ResultMatrixStore.v"] \
 [file normalize "${origin_dir}/src/design/common/SimpleDualRam.v"] \
 [file normalize "${origin_dir}/src/design/common/SimpleRam.v"] \
 [file normalize "${origin_dir}/src/design/rendering/ToolbarVGA.v"] \
 [file normalize "${origin_dir}/src/design/uart/UartTx.v"] \
 [file normalize "${origin_dir}/src/design/driver/VGAControl.v"] \
 [file normalize "${origin_dir}/src/design/matrix/VisitedMatrixStore.v"] \
 [file normalize "${origin_dir}/src/design/rendering/WaveformPlot.v"] \
 [file normalize "${origin_dir}/src/design/interaction/WireDrawMode.v"] \
 [file normalize "${origin_dir}/src/design/Keyboard/one_bit_adder.v"] \
 [file normalize "${origin_dir}/src/design/common/ExtractComponentNodesCombPkg.sv"] \
 [file normalize "${origin_dir}/src/design/solver/FloodingBackendWrapper.sv"] \
 [file normalize "${origin_dir}/src/design/common/FloodingCombPkg.sv"] \
 [file normalize "${origin_dir}/src/design/solver/extract_component_nodes.sv"] \
 [file normalize "${origin_dir}/src/design/solver/flooding_core.sv"] \
 [file normalize "${origin_dir}/src/design/rendering/MouseDisplay.vhd"] \
 [file normalize "${origin_dir}/src/design/driver/Mouse_Control.vhd"] \
 [file normalize "${origin_dir}/src/design/driver/Ps2Interface.vhd"] \
 [file normalize "${origin_dir}/src/design/rendering/GlobalRender_top.v"] \
 [file normalize "${origin_dir}/src/ip/floating_point_fma/floating_point_fma.xci"] \
 [file normalize "${origin_dir}/src/ip/floating_point_div/floating_point_div.xci"] \
 [file normalize "${origin_dir}/src/design/uart/Hex7SegMux.v"] \
 [file normalize "${origin_dir}/src/design/solver_board/UartRx.v"] \
 [file normalize "${origin_dir}/src/design/floating_point/fpo_div.v"] \
 [file normalize "${origin_dir}/src/design/floating_point/fpo_fma.v"] \
 [file normalize "${origin_dir}/src/design/solver_board/BcdUnitToFp32Rom.sv"] \
 [file normalize "${origin_dir}/src/design/solver_board/SolverDcPipeline.sv"] \
 [file normalize "${origin_dir}/src/design/matrix/SolverMatrixStore.sv"] \
 [file normalize "${origin_dir}/src/design/solver_board/SolverUartLineTransmitter.sv"] \
 [file normalize "${origin_dir}/src/design/matrix/SolverVectorStore.sv"] \
 [file normalize "${origin_dir}/src/design/common/StampingCombPkg.sv"] \
 [file normalize "${origin_dir}/src/design/common/StampingNetlistStore.sv"] \
 [file normalize "${origin_dir}/src/design/solver_board/UartLineAssembler.sv"] \
 [file normalize "${origin_dir}/src/design/solver_board/UartPacketParser.sv"] \
 [file normalize "${origin_dir}/src/design/solver/solve_core_dc.sv"] \
 [file normalize "${origin_dir}/src/design/solver_board/SolverBoard_top.sv"] \
 [file normalize "${origin_dir}/src/design/Dashboard/TextBox.v"] \
 [file normalize "${origin_dir}/src/design/Dashboard/CompactDigitROM.v"] \
 [file normalize "${origin_dir}/src/design/Dashboard/MatrixDisplay.v"] \
 [file normalize "${origin_dir}/src/design/uart/UART_FrameDemo_top.v"] \
 [file normalize "${origin_dir}/src/ip/floating_point_to_fixed_16_16/floating_point_to_fixed_16_16.xci"] \
 [file normalize "${origin_dir}/src/design/Keyboard/Keyboard.v"] \
 [file normalize "${origin_dir}/src/design/floating_point/fpo_tofixed.v"] \
 [file normalize "${origin_dir}/src/design/matrix/lu_core.sv"] \
 [file normalize "${origin_dir}/src/design/common/ClockDividerMs.v"] \
 [file normalize "${origin_dir}/src/design/matrix/LUdecomp.v"] \
 [file normalize "${origin_dir}/src/design/matrix/bmatrixStore.v"] \
 [file normalize "${origin_dir}/src/design/Dashboard/TextDisplay.v"] \
 [file normalize "${origin_dir}/src/design/matrix/PortGridStore.v"] \
 [file normalize "${origin_dir}/src/design/common/CanvasBufferRam.v"] \
 [file normalize "${origin_dir}/src/design/matrix/matrixStore.v"] \
 [file normalize "${origin_dir}/src/design/Dashboard/DynamicTextDisplay.v"] \
 [file normalize "${origin_dir}/src/design/solver_board/bcd_unit_to_fp32_rom.mem"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/src/design/common/ExtractComponentNodesCombPkg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/solver/FloodingBackendWrapper.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/common/FloodingCombPkg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/solver/extract_component_nodes.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/solver/flooding_core.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/rendering/MouseDisplay.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/design/driver/Mouse_Control.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/design/driver/Ps2Interface.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/src/ip/floating_point_fma/floating_point_fma.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/src/ip/floating_point_div/floating_point_div.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/src/design/solver_board/BcdUnitToFp32Rom.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/solver_board/SolverDcPipeline.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/matrix/SolverMatrixStore.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/solver_board/SolverUartLineTransmitter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/matrix/SolverVectorStore.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/common/StampingCombPkg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/common/StampingNetlistStore.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/solver_board/UartLineAssembler.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/solver_board/UartPacketParser.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/solver/solve_core_dc.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/solver_board/SolverBoard_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/ip/floating_point_to_fixed_16_16/floating_point_to_fixed_16_16.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/src/design/matrix/lu_core.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/solver_board/bcd_unit_to_fp32_rom.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "GlobalRender_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/constraint/basys3.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/src/constraint/basys3.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/constraint/basys3_solver_board.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/src/constraint/basys3_solver_board.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xc7a35tcpg236-1" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/src/testbench/SolveCoreDc_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/VisitedMatrixStore_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/StampingCombPkg_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/InteractionController_test.v"] \
 [file normalize "${origin_dir}/src/testbench/StampingNetlistStore_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/FloodingCombPkg_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/FloodQueueStore_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/Canvas_test.v"] \
 [file normalize "${origin_dir}/src/testbench/SolverVectorStore_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/misc/CounterQuiz_test.v"] \
 [file normalize "${origin_dir}/src/testbench/FloodingCore_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/StampingVectorStore_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/LU_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/CircuitCanvas_left_edge_test.v"] \
 [file normalize "${origin_dir}/src/testbench/PingPongBuffer_test.v"] \
 [file normalize "${origin_dir}/src/testbench/InteractionCanvas_test.v"] \
 [file normalize "${origin_dir}/src/testbench/PortGridStore_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/DynamicTextDisplay_tb.v"] \
 [file normalize "${origin_dir}/src/testbench/StampingMatrixStore_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/FP_test.v"] \
 [file normalize "${origin_dir}/src/testbench/LU_hls_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/SolverMatrixStore_test.sv"] \
 [file normalize "${origin_dir}/src/testbench/FP_wrapper_test.v"] \
 [file normalize "${origin_dir}/src/testbench/ResultMatrixStore_test.sv"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/src/testbench/SolveCoreDc_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/VisitedMatrixStore_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/StampingCombPkg_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/StampingNetlistStore_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/FloodingCombPkg_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/FloodQueueStore_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/SolverVectorStore_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/FloodingCore_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/StampingVectorStore_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/LU_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/PortGridStore_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/StampingMatrixStore_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/LU_hls_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/SolverMatrixStore_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/testbench/ResultMatrixStore_test.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "SolveCoreDc_test" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a35tcpg236-1 -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2018" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7a35tcpg236-1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a35tcpg236-1 -flow {Vivado Implementation 2018} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2018" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7a35tcpg236-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
